dtolnay/async-trait

src/expand.rs
tests/test.rs

Work around `where <T>` parser restriction

---

src/args.rs
tests/test.rs

Rename local to ?Send

---

README.md
src/lib.rs
tests/test.rs

`async_await` is stabilized in rust-lang/rust#63209

Remove async_await feature gate

---

.travis.yml
tests/executor/mod.rs
tests/test.rs

Add test for async specialization

---

src/expand.rs
src/lifetime.rs
tests/test.rs

Support trait with lifetime

---

src/receiver.rs
tests/test.rs

Support Self used as expr inside trait method body

---

.travis.yml

https://github.com/rust-lang/rust/issues/64964 is breaking our tests.
```console
error: internal compiler error: src/librustc/ich/impls_ty.rs:100: StableHasher: unexpected region '_#0r
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.40.0-nightly (702b45e40 2019-10-01) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental
note: some of the compiler flags provided by cargo are hidden
```

Pin Travis to nightly-2019-10-01

---

src/expand.rs
tests/test.rs

And not to a user defined module or import named `core`

fix: Always refer to the core crate

---

Cargo.toml
src/expand.rs
src/receiver.rs
tests/test.rs

Allows to define static methods on trait with `where Self: ...` specified. Example:
```rust
use async_trait::async_trait;
#[async_trait]
trait GetFive where Self: Sized {
async fn get_five() -> u8 {
5
}
}
struct Empty {}
impl GetFive for Empty {}
#[tokio::main]
async fn main() {
assert_eq!(Empty::get_five().await, 5);
}
```
Current behaviour: 
```
error[E0412]: cannot find type `AsyncTrait` in this scope
--> src/main.rs:5:1
|
5 | #[async_trait]
| ^^^^^^^^^^^^^^ not found in this scope
error: aborting due to previous error
For more information about this error, try `rustc --explain E0412`.
```

Fix static methods defined in trait with `where Self: ...` specified

---

src/expand.rs
tests/test.rs

async-trait currently doesnt work with const generics. this pull request tries to fix this
closes #57

add support for const generics

---

src/expand.rs

Similarly to #21 and #51 suppresses yet another `clippy::pedantic` complaining lint:
```
error: this type has already been used as a bound predicate
--> crates/my-crate/src/conn.rs:15:1
|
15 | #[async_trait(?Send)]
| ^^^^^^^^^^^^^^^^^^^^^
|
= note: `-D clippy::type-repetition-in-bounds` implied by `-D clippy::pedantic`
= help: consider combining the bounds: `T: ToStatement`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#type_repetition_in_bounds
```

Suppress clippy::type_repetition_in_bounds

---

Cargo.toml
tests/test.rs

This PR intends to allow detecting future breakage of the [tracing](https://github.com/tokio-rs/tracing) crate and should allow us to finally close the bug #45.
To put in a it more context, the `#[tracing::instrument]` proc-macro is currently detecting whether the function the user wishes to instrument was generated by async-trait, and to instrument the internal async fn in such case, instead of the wrapper generated by async-trait.
Until recently, tracing didn't have that detection mecanism, but since this was recently added in tracing-attributes 0.1.8 (or tracing 0.1.14), it makes sense to add some tests here too to help detect early breaking changes.

Add a "reverse" test to prevent breakage of the `tracing` crate

---

src/receiver.rs
tests/ui/self-span.rs
tests/ui/self-span.stderr

The following code:
```rust
use async_trait::async_trait;
pub struct Struct {}
#[async_trait]
pub trait Trait {
async fn method(self);
}
#[async_trait]
impl Trait for Struct {
async fn method(self) {
let _: Self = Self;
}
}
```
The error message points to wrong span:
```text
error[E0423]: expected value, found struct `Struct`
--> src/lib.rs:11:16
|
11 | impl Trait for Struct {
|                ^^^^^^ did you mean `(Struct { /* fields */ })`?
|
```
This PR fixes span of Self keyword to make the error message to point to the correct span:
```text
error[E0423]: expected value, found struct `Struct`
--> $DIR/self-span.rs:14:23
|
3  | pub struct Struct {}
| -------------------- `Struct` defined here
...
14 |         let _: Self = Self;
|                       ^^^^ did you mean `Struct { /* …
```

Preserve span of Self keyword

---

src/expand.rs
tests/test.rs

Preserve the span of self argument

---

src/receiver.rs
tests/ui/self-span.rs
tests/ui/self-span.stderr

A similar case to #102.
The following code:
```rust
pub enum E {
V {}
}
#[async_trait]
impl Trait for E {
async fn method(self) {
let _: () = self;
let _: Self = Self::V;
}
}
```
The error message points to call-site span:
```text
error[E0533]: expected unit struct, unit variant or constant, found struct variant `#[async_trait]`
--> $DIR/self-span.rs:22:1
|
22 | #[async_trait]
| ^^^^^^^^^^^^^^
|
```
This PR fixes span of `<` and `>` tokens of `QSelf` to make the error message to point to the correct span:
```text
error[E0533]: expected unit struct, unit variant or constant, found struct variant `Self::V`
--> $DIR/self-span.rs:26:23
|
26 |         let _: Self = Self::V;
|                       ^^^^^^^
```
(this originally caught in https://github.com/taiki-e/pin-project/pull/249. also …

Propagate the span of Self keyword to QSelf

---

src/expand.rs
src/lifetime.rs
tests/test.rs

Fixes #106
Currently, these are only applying for function arguments, but this PR change this to also apply to trait and implementor's paths.
```rust
impl Trait<'_> for &Type<'_> {}
// converted to:
impl<'impl_life0, 'impl_life1, 'impl_life2> 
Trait<'impl_life0> for &'impl_life1 Type<'impl_life2> {}
```

Replace elided lifetimes to explicit lifetimes in trait impl

---

README.md

Update the lifetimes in the example to be `'async_trait`, rather than `'async`. This brings the example into sync with `transform_sig()`.

Update async lifetime in README.md

---

src/expand.rs

Closes #118.
Rustc is inserting needless parens into the macro input before calling async_trait, then warning the user that they wrote needless parens. See https://github.com/dtolnay/async-trait/issues/118#issuecomment-673083481.

Work around unused_parens rustc issue

---

src/expand.rs
tests/test.rs

At the moment, if trait has type/const parameters with default values and also has a default method implementation, like the following:
```rust
#[async_trait]
trait Trait<T = ()> {
async fn f(&self) -> &str
where
T: 'async_trait,
{
"default"
}
}
```
The expanded code is:
```rust
trait Trait<T = ()> {
#[must_use]
fn f<'life0, 'async_trait>(
&'life0 self,
) -> ::core::pin::Pin<
Box<dyn ::core::future::Future<Output = &str> + ::core::marker::Send + 'async_trait>,
>
where
T: 'async_trait,
'life0: 'async_trait,
Self: ::core::marker::Sync + 'async_trait,
{
#[allow(
unused_parens,
clippy::missing_docs_in_private_items,
clippy::needless_lifetimes,
clippy::ptr_arg,
clippy::trivially_copy_pass_by_ref,
clippy::type_repetition_in_bounds,
clippy::used_underscore_binding
)]
async fn __f<
'async_trait, …
```

Remove defaults from trait params when using them in function definition

---

src/expand.rs
tests/test.rs

The wrapper future-returning function we generate simply forwards all arguments to the async inner function, so we expect it always uses all arguments, including ones that are named with an underscore.
Fixes #129.

Suppress used_underscore_binding on wrapper function

---

src/expand.rs
tests/test.rs

Resolve let_unit_value pedantic lint in generated code

---

src/expand.rs
tests/test.rs

Prepend early return to force unsize coercion

---

src/expand.rs
tests/test.rs

Support for impl Trait in associated type (type_alias_impl_trait)

---

Cargo.toml
tests/test.rs

Fixed in the tracing crate by https://github.com/tokio-rs/tracing/pull/1291.

Re-enable tracing attribute test

---

Cargo.toml
src/receiver.rs
tests/test.rs

Compatibility with tokio::select

---

Cargo.toml
src/expand.rs
tests/test.rs

1. Not sure if we want to use `Eq` on `syn::Path` or just break down the path's elements and compare idents ourselves.
2. Should I add cases for `::std::marker::Path`? The list kinda blows up, so I would say most explicit path and least explicit ident is okay for now.
Fixes #169

Allow fully elaborated `::core::marker::Trait` supertraits

---

tests/test.rs

As of nightly-2021-07-29:
```console
error[E0557]: feature has been removed
--> tests/test.rs:3:33
|
3 |     feature(min_specialization, min_type_alias_impl_trait)
|                                 ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
|
= note: removed in favor of full type_alias_impl_trait
error[E0658]: `impl Trait` in type aliases is unstable
--> tests/test.rs:1299:22
|
1299 |         type Assoc = impl Sized;
|                      ^^^^^^^^^^
|
= note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
= help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable
```

Feature min_type_alias_impl_trait renamed to type_alias_impl_trait

---

tests/ui/consider-restricting.rs
tests/ui/consider-restricting.stderr

https://github.com/rust-lang/rust/issues/93828

Add ui test to capture current situation of rust issue 93828

---

src/expand.rs
tests/ui/consider-restricting.stderr

I experimented with this as an alternative to #191. There are a few diagnostics that this still makes worse, but I think this one is an improvement often enough that I think it's worth trying.
Here is what it does to the expanded code from the ui test:
```diff
-  fn publish<'life0, 'async_trait, T: IntoUrl>(
+  fn publish<'life0, 'async_trait, T>(
&'life0 self,
url: T,
) -> ::core::pin::Pin<Box<dyn ::core::future::Future<Output = ()> + ::core::marker::Send + 'async_trait>>
where
-      T: 'async_trait,
+      T: 'async_trait + IntoUrl,
'life0: 'async_trait,
Self: 'async_trait,
{…}
```
Since we've inserted `'async_trait +` at the beginning of the bounds list, instead of `+ 'async_trait` at the end, when rustc goes to add more bounds they'll appear correctly after the last user-written …

Move bounds from generic param list to where-clause after 'async_trait bound

---

Cargo.toml
src/expand.rs
src/lifetime.rs
tests/test.rs

Add 'async_trait lifetime to impl Trait arguments

---

src/lifetime.rs
tests/test.rs

Use parentheses to disambiguate impl Trait

---

src/lifetime.rs
tests/test.rs

Parenthesize other cases that require parens around impl Trait

---

tests/test.rs

```console
$ MIRIFLAGS=-Zmiri-strict-provenance cargo miri test
test issue45::tracing ... error: unsupported operation: integer-to-pointer casts and `ptr::from_exposed_addr` are not supported with `-Zmiri-strict-provenance`
--> github.com-1ecc6299db9ec823/once_cell-1.12.0/src/imp_std.rs:175:30
|
175 |             let mut waiter = (queue & !STATE_MASK) as *const Waiter;
|                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ integer-to-pointer casts and `ptr::from_exposed_addr` are not supported with `-Zmiri-strict-provenance`
|
= help: use Strict Provenance APIs (https://doc.rust-lang.org/nightly/std/ptr/index.html#strict-provenance, https://crates.io/crates/sptr) instead
= note: inside `<once_cell::imp::Guard as std::ops::Drop>::drop` at …
```

Disable test of tracing attrs on miri due to once_cell

---

.github/workflows/ci.yml

https://github.com/rust-lang/rust-clippy/issues/9089
```console
error: internal compiler error: compiler/rustc_typeck/src/collect.rs:1896:13: to get the signature of a closure, use `substs.as_closure().sig()` not `fn_sig()`
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/46b8c23f3eb5e4d0e0aa27eb3f20d5b8fc3ed51f/compiler/rustc_errors/src/lib.rs:1391:9
stack backtrace:
0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
1: std::panic::panic_any::<rustc_errors::ExplicitBug>
2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
3: <rustc_errors::Handler>::bug::<&alloc::string::String>
4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>
5: …
```

Temporarily disable clippy on tests due to ICE

---

src/expand.rs

In preparation for #210 which is going to require **both** `Send` **and** `Sync` bound on Self.

Generalize support for inferred multiple bounds

---

src/expand.rs
tests/test.rs

Infer Sync+Send bound for Arc<Self> methods with default body

---

src/expand.rs
tests/test.rs

Fixes #226.
It feels rare to have attributes on parameters, I can't imagine a concrete scenario where forwarding all attributes is undesirable.
We could filter the attributes that are forwarded to only the `#[cfg(..)]` ones.

Forward attributes on `impl` function parameters to variable declaration.

---

src/expand.rs
src/lifetime.rs
tests/ui/lifetime-defined-here.rs
tests/ui/lifetime-defined-here.stderr

Improve spans of named lifetimes generated from elided lifetimes

---

src/expand.rs
tests/test.rs

Bypass Sync bound implied by non-existent drop of reference

---

src/expand.rs
tests/test.rs

Suppress async_yields_async clippy correctness lint in generated code

---

src/expand.rs
src/lifetime.rs
tests/test.rs

This reverts PR #107. The code from that PR is no longer necessary for 2 reasons.
1. As of https://github.com/rust-lang/rust/pull/85499 in Rust 1.56.0, the problem described in #106 involving `FnOnce(&Self::ThreadPool)` vs `FnOnce(&<&P as ProcessPool>::ThreadPool)` does not occur. These two trait bounds mean the same thing to sufficiently new versions of Rust.
2. As of #143 in async-trait 0.1.43 we no longer replace `FnOnce(&Self::ThreadPool)` to `FnOnce(&<&P as ProcessPool>::ThreadPool)` in generated code, so even with old rustc, the old problem does not occur.
Fixes #238.

Delete replacement of elided lifetimes in impl heading

---

README.md
build.rs
src/lib.rs

Update documentation to discuss object safety in Rust 1.75+

---

README.md
src/lib.rs

Update for the new expansion since #143.

Update explanation to show async block expansion

---

Cargo.toml
tests/test.rs

The pull request that this links to was landed and release in once_cell 1.13.1.

Re-enable tracing integration test under Miri

---

src/expand.rs
tests/test.rs

Fixes #259. The new lints in nightly-2024-03-05 are resulting from https://github.com/rust-lang/rust/pull/121528.

Ignore unused_qualifications rustc lint in generated code

---

src/expand.rs
tests/test.rs

The generated code for function bodies produces an `unreachable_code` warning if the function has a `!` return type.
The offending bit is:
```rust
if let Some(__ret) == None::<!> {
// unreachable
}
```
This PR fixes the warning by simply adding `#[allow(unreachable_code)]` to the return statement. It also adds a test for it.
This problem can only be triggered on nightly with the `never_type` feature enabled, but it is easy to fix here.

Fix unreachable code warning for functions that return `!`

---

tests/test.rs

Since nightly-2024-06-05 (https://github.com/rust-lang/rust/pull/125380).
```console
warning: unknown lint: `where_clauses_object_safety`
--> tests/test.rs:1383:8
|
1383 | #[deny(where_clauses_object_safety)]
|        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unknown_lints)]` on by default
```

Former where_clauses_object_safety lint is now hard error

---

Cargo.toml

Effectively unsets `derive` feature (and `default`, obviously), removing unused feature.

syn: remove derive feature

---

src/expand.rs

https://github.com/rust-lang/rust/pull/129207 added this lint:
```console
warning: elided lifetime has a name
--> tests/test.rs:1118:30
|
1118 |         async fn f(&self) -> &str
|                    -         ^ this elided lifetime gets resolved as `'life0`
|                    |
|                    lifetime `'life0` declared here
|
= note: `#[warn(elided_named_lifetimes)]` on by default
```
For #\[async_trait\] this is not useful because the macro needs to give names to some lifetimes which are not named in the user's code.

Ignore nightly's new elided_named_lifetimes lint in generated code

---

src/expand.rs
tests/test.rs

Ignore needless_arbitrary_self_type clippy lint in generated code

---

.github/workflows/ci.yml
Cargo.toml
src/expand.rs
tests/test.rs

Support impl Trait in return type

---

src/expand.rs
tests/test.rs

Omit `Self: 'async_trait` bound in impl when not needed by signature

---

tests/test.rs

https://github.com/rust-lang/rust/issues/130852

Update 'object safe' -> 'dyn compatible' naming in tests

---

src/expand.rs
tests/test.rs

Fix lifetime bounding on generic parameters that have cfg
