- src/expand.rs
- tests/test.rs
> Include generic parameters from enclosing block

- src/expand.rs
- src/lib.rs
> Support no_std

- src/expand.rs
- src/receiver.rs
- tests/test.rs
> Fix Self argument in trait method without self

- src/expand.rs
- tests/test.rs
> Support arbitrary self types

- README.md
- src/expand.rs
- src/lib.rs
- tests/test.rs
I haven't tested this in our codebase yet, but I believe this will work
> Add Non-Send/Sync support

- src/expand.rs
- src/lifetime.rs
- tests/test.rs
> Work around lifetime that does not appear in bounds

- src/expand.rs
- tests/test.rs
> Propagate mutability of `mut self` argument

- src/expand.rs
- tests/test.rs
> Fix disagreement between trait and impl about whether signature contains Self

- src/expand.rs
And not the `#[async_trait]` attribute. Don't have a good way to test
this automatically unfortunately.
Changes the errors for the following code
```rust
use async_trait::async_trait;
trait Test {
async fn test(&self) {
let m = std::sync::Mutex::new(());
let _lock = m.lock().unwrap();
self.test().await;
}
}
```
```
error[E0277]: `std::sync::MutexGuard<'_, ()>` cannot be sent between threads safely
--> tests\fail.rs:5:14
|
5 | #[async_trait]
|              ^ `std::sync::MutexGuard<'_, ()>` cannot be sent between threads safely
|
= help: within `impl std::future::Future`, the trait `std::marker::Send` is not implemented for `std::sync::MutexGuard<'_, ()>`
= note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2, 't3> {&'r Self, std::sync::Mutex<()>, …
```
> fix: Make "Send is not implemented" errors point to the block

- src/expand.rs
> Suppress missing_docs_in_private_items

- src/receiver.rs
- tests/test.rs
> Handle `Self` in expression position

- src/receiver.rs
- tests/test.rs
> Handle Self in expression position with braced fields

- README.md
Emoji don't render on crates.io
> Embed emoji in readme instead of depending on GFM

- src/receiver.rs
- tests/ui/delimiter-span.rs
- tests/ui/delimiter-span.stderr
> Preserve span of Group tokens in macro input

- src/receiver.rs
- tests/test.rs
> Handle Self keyword inside macro invocations

- src/receiver.rs
- tests/test.rs
> Support self in macro_rules!

- src/receiver.rs
- tests/test.rs
> Handle Self:: segment in patterns

- src/expand.rs
- tests/test.rs
> Handle longhand method receiver syntax

- src/expand.rs
- tests/test.rs
> Don't trigger non_snake_case lint in trait impls

- src/receiver.rs
- tests/test.rs
> Support Self:: segment in more places

- src/expand.rs
- tests/test.rs
- tests/ui/bare-trait-object.rs
- tests/ui/bare-trait-object.stderr
> Fix failure to parse some types of trait objects

- src/receiver.rs
- tests/test.rs
> Fix handling of Self keyword inside macro invocations

- .github/workflows/ci.yml
- src/expand.rs
- tests/test.rs
> Add some more clippy suppressions to generated code

- src/expand.rs
- tests/test.rs
> Suppress trivially_copy_pass_by_ref

- src/receiver.rs
- tests/test.rs
Addresses https://github.com/dtolnay/async-trait/issues/92#issuecomment-683370136, see https://github.com/dtolnay/async-trait/issues/92#issuecomment-683372182 for details.
> Fix HasSelf visitor to visit Self keyword inside macro invocations

- src/expand.rs
- src/lib.rs
- tests/test.rs
> Insert AsyncTrait parameter prior to const parameters

- src/expand.rs
- tests/test.rs
> Suppress type_complexity lint in generated code

- src/expand.rs
- tests/test.rs
> Avoid items_after_statements lint in generated code

- src/receiver.rs
- tests/test.rs
> Preserve `self` as segment of path

- Cargo.toml
- src/expand.rs
> Drop syn/extra-traits dependency from PR 170

- src/expand.rs
> Recognize std::marker::Trait bound in addition to core::marker::Trait

- src/expand.rs
> Tweak some spans to try for meaningful click-through on method names

- src/expand.rs
- tests/test.rs
> Make expansion of nested `_` and `..` patterns edition independent

- Cargo.toml
- build.rs
Context: https://blog.rust-lang.org/2024/05/06/check-cfg.html
> Resolve unexpected_cfgs warning
